#!/usr/bin/env node
const Web3 = require('web3')
const args = require('optimist').string("address").argv;
const truffleContract = require("truffle-contract");

let rpc = args.rpc ? args.arpc : "http://localhost:8545"
let conf = args.abi ? require(args.abi) : require('./build/contracts/CryptoCards.json');
let abi = conf.abi;
let address = args.address;

const web3 = new Web3(new Web3.providers.HttpProvider(rpc));

const contract = truffleContract({abi});
contract.setProvider(web3.currentProvider);
cards = contract.at(address);


let alice = web3.eth.accounts[0];
let bob = web3.eth.accounts[2];

cards.register({from: alice, gas: 700000});
cards.register({from: bob, gas: 700000});

cards.depositToPlasma(3, {from: alice, gas: 300000});
cards.depositToPlasma(4, {from: alice, gas: 300000});
// cards.depositToPlasmaWithData(7, '150x123WTF', {from: bob, gas: 300000});
// cards.depositToPlasmaWithData(6, 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCDFGH', {from: bob, gas: 300000});
